[theme]
primaryColor = "#800000"        # University of Chicago maroon
backgroundColor = "#FFFFFF"     # White background
secondaryBackgroundColor = "#F5F5F5"  # Light gray
textColor = "#262730"          # Dark text

[server]
headless = true
port = 8501